#pragma once

/**
 * @file Exceptions.hpp
 * @brief Exception types and error translators used by the IRC server.
 * @details Defines the `PersonalizedException` base class and several derived
 *  exception types that carry source file and line information. Also provides
 *  functions to translate system error codes from socket, bind, and listen
 *  operations into the corresponding exception types.
 * 
 * @date 2026-07-20
 * @author Jesus Leiva Guerrero
 * @author Emilio Garcia Burgos
 * @author Lilith Estévez Boeta
 */

#include <stdexcept>

using std::exception;
using std::string;

/**
 * @defgroup ExceptionTypes Exception Types
 * @brief Custom exception types for the IRC server.
 * @details This group contains the `PersonalizedException` base class and
 *  several derived exception types that represent specific error conditions
 *  encountered during server operation. Each exception type carries the source
 *  file and line number where it was thrown, allowing for detailed error
 *  reporting and debugging.
 * 
 * @{
 */

void manageErrorsFromSocket(int error, const char* file, int line);
void manageErrorsFromBind(int error, const char* file, int line);
void manageErrorsFromListen(int error, const char* file, int line);

/**
 * @struct PersonalizedException
 * @brief Base class for server exceptions carrying source location metadata.
 * @details Derived exceptions use the stored file and line to include the
 *  origin of the failure in their `what()` message.
 */
struct PersonalizedException : public exception {
	protected:
		string			file;			///< Source file where the exception was created.
		int				line;			///< Source line where the exception was created.
		mutable string	errorMessage;	///< Message generated by the last `what()` call.
	public:
		PersonalizedException(const char* file, int line);
		~PersonalizedException() throw();
};

/** @brief Represents an unclassified server error. */
struct UnknownException : public PersonalizedException {
	UnknownException(const char* file, int line);
	const char* what() const throw();
};

/** @brief Indicates that the operation lacks the required permissions. */
struct NotEnoughPermissionsException : public PersonalizedException {
	NotEnoughPermissionsException(const char* file, int line);
	const char* what() const throw();
};

/** @brief Indicates that the system lacks memory for the operation. */
struct NotEnoughMemoryException : public PersonalizedException {
	NotEnoughMemoryException(const char* file, int line);
	const char* what() const throw();
};

/** @brief Indicates that the process or system has no free file descriptors. */
struct NotEnoughFileDescriptorsException : public PersonalizedException {
	NotEnoughFileDescriptorsException(const char* file, int line);
	const char* what() const throw();
};

/** @brief Indicates that the requested IP protocol is unsupported. */
struct UnsupportedIPProtocolException : public PersonalizedException {
	UnsupportedIPProtocolException(const char* file, int line);
	const char* what() const throw();
};

/** @brief Indicates that the requested port is already in use. */
struct PortInUseException : public PersonalizedException {
	PortInUseException(const char* file, int line);
	const char* what() const throw();
};

/** @brief Indicates that a system call received an invalid file descriptor. */
struct InvalidFileDescriptorException : public PersonalizedException {
	InvalidFileDescriptorException(const char* file, int line);
	const char* what() const throw();
};

/** @brief Indicates that the socket was already bound to an address. */
struct AlredyLinkedFileDescriptorException : public PersonalizedException {
	AlredyLinkedFileDescriptorException(const char* file, int line);
	const char* what() const throw();
};

/** @brief Indicates that a file descriptor is not associated with a socket. */
struct FileDescriptorIsNotSocketException : public PersonalizedException {
	FileDescriptorIsNotSocketException(const char* file, int line);
	const char* what() const throw();
};

/** @brief Indicates that the socket does not support the listen operation. */
struct SocketNotSupportListenException : public PersonalizedException {
	SocketNotSupportListenException(const char* file, int line);
	const char* what() const throw();
};

/**
 * @}
 */
